Flight.create(airline: "Delta Airline", origin: "New York City", destination: "Los Angeles", flight_date_time: "January 30th, 2021, 2:30PM")
Flight.create(airline: "American Airline", origin: "Boston", destination: "Seattle", flight_date_time: "February 1st, 2021, 9:00AM")
Flight.create(airline: "United Airline", origin: "San Francisco", destination: "Denver", flight_date_time: "January 31st, 2021, 11:30AM")
Flight.create(airline: "South West", origin: "Washington DC", destination: "Miami", flight_date_time: "February 1st, 2021, 1:00PM")
Flight.create(airline: "Alaska Airline", origin: "Portland", destination: "San Diego", flight_date_time: "January 29th, 2021, 10:30AM")
Flight.create(airline: "JetBlue Airline", origin: "Dallas", destination: "Atlanta", flight_date_time: "February 2nd, 2021, 8:30AM")
Flight.create(airline: "Hawaiian Airlines ", origin: "Hawai", destination: "Austin", flight_date_time: "February 4th, 2021, 12:30PM")
Flight.create(airline: "Delta", origin: "Dallas", destination: "Houston", flight_date_time: "January 31th, 2021, 4:30PM")
Flight.create(airline: "American Airline", origin: "South Carolina", destination: "New Orleans", flight_date_time: "February 5th, 2021, 3:30PM")
Flight.create(airline: "United Airline", origin: "Phoenix", destination: "New York City", flight_date_time: "January 31st, 2021, 11:30AM")
